<?php

 /**
 * Implementation of hook_wysiwyg_editor_settings_alter().
 *
 * Emulate the body classes on a node page so the editor reflects more closely
 * how text will be rendered on actual page
 */
function pp_helper_wysiwyg_editor_settings_alter(&$settings, $context) {
  if ($context['profile']->editor == 'tinymce') {
    $settings['body_class'] = 'node';
  }
}

/**
* Implementation of hook_ctools_plugin_directory().
*/
function pp_helper_ctools_plugin_directory( $module, $plugin ){
    
  if( $module == 'page_manager' || $module == 'panels' ){
    return 'plugins/' . $plugin;
  }
}